# Generated by Django 2.2.6 on 2019-11-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0002_auto_20191114_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
