# Generated by Django 2.2.6 on 2019-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0006_auto_20191118_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/anonymous-user.png', null=True, upload_to='user_images'),
        ),
    ]
